Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/belka/Library/Python/3.10/lib/python/site-packages/nbclient/client.py", line 1265, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/belka/Library/Python/3.10/lib/python/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/belka/Library/Python/3.10/lib/python/site-packages/nbclient/client.py", line 703, in async_execute
    await self.async_execute_cell(
  File "/Users/belka/Library/Python/3.10/lib/python/site-packages/nbclient/client.py", line 1021, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/belka/Library/Python/3.10/lib/python/site-packages/nbclient/client.py", line 915, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
buildings.to_file('data/spb_central_build.gpkg')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[13], line 1[0m
[0;32m----> 1[0m [43mbuildings[49m[38;5;241;43m.[39;49m[43mto_file[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mdata/spb_central_build.gpkg[39;49m[38;5;124;43m'[39;49m[43m)[49m

File [0;32m/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/geopandas/geodataframe.py:1263[0m, in [0;36mGeoDataFrame.to_file[0;34m(self, filename, driver, schema, index, **kwargs)[0m
[1;32m   1172[0m [38;5;250m[39m[38;5;124;03m"""Write the ``GeoDataFrame`` to a file.[39;00m
[1;32m   1173[0m 
[1;32m   1174[0m [38;5;124;03mBy default, an ESRI shapefile is written, but any OGR data source[39;00m
[0;32m   (...)[0m
[1;32m   1259[0m 
[1;32m   1260[0m [38;5;124;03m"""[39;00m
[1;32m   1261[0m [38;5;28;01mfrom[39;00m [38;5;21;01mgeopandas[39;00m[38;5;21;01m.[39;00m[38;5;21;01mio[39;00m[38;5;21;01m.[39;00m[38;5;21;01mfile[39;00m [38;5;28;01mimport[39;00m _to_file
[0;32m-> 1263[0m [43m_to_file[49m[43m([49m[38;5;28;43mself[39;49m[43m,[49m[43m [49m[43mfilename[49m[43m,[49m[43m [49m[43mdriver[49m[43m,[49m[43m [49m[43mschema[49m[43m,[49m[43m [49m[43mindex[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/geopandas/io/file.py:572[0m, in [0;36m_to_file[0;34m(df, filename, driver, schema, index, mode, crs, engine, **kwargs)[0m
[1;32m    569[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124m'[39m[38;5;124mmode[39m[38;5;124m'[39m[38;5;124m should be one of [39m[38;5;124m'[39m[38;5;124mw[39m[38;5;124m'[39m[38;5;124m or [39m[38;5;124m'[39m[38;5;124ma[39m[38;5;124m'[39m[38;5;124m, got [39m[38;5;124m'[39m[38;5;132;01m{[39;00mmode[38;5;132;01m}[39;00m[38;5;124m'[39m[38;5;124m instead[39m[38;5;124m"[39m)
[1;32m    571[0m [38;5;28;01mif[39;00m engine [38;5;241m==[39m [38;5;124m"[39m[38;5;124mfiona[39m[38;5;124m"[39m:
[0;32m--> 572[0m     [43m_to_file_fiona[49m[43m([49m[43mdf[49m[43m,[49m[43m [49m[43mfilename[49m[43m,[49m[43m [49m[43mdriver[49m[43m,[49m[43m [49m[43mschema[49m[43m,[49m[43m [49m[43mcrs[49m[43m,[49m[43m [49m[43mmode[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    573[0m [38;5;28;01melif[39;00m engine [38;5;241m==[39m [38;5;124m"[39m[38;5;124mpyogrio[39m[38;5;124m"[39m:
[1;32m    574[0m     _to_file_pyogrio(df, filename, driver, schema, crs, mode, [38;5;241m*[39m[38;5;241m*[39mkwargs)

File [0;32m/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/geopandas/io/file.py:601[0m, in [0;36m_to_file_fiona[0;34m(df, filename, driver, schema, crs, mode, **kwargs)[0m
[1;32m    597[0m     crs_wkt [38;5;241m=[39m crs[38;5;241m.[39mto_wkt([38;5;124m"[39m[38;5;124mWKT1_GDAL[39m[38;5;124m"[39m)
[1;32m    598[0m [38;5;28;01mwith[39;00m fiona[38;5;241m.[39mopen(
[1;32m    599[0m     filename, mode[38;5;241m=[39mmode, driver[38;5;241m=[39mdriver, crs_wkt[38;5;241m=[39mcrs_wkt, schema[38;5;241m=[39mschema, [38;5;241m*[39m[38;5;241m*[39mkwargs
[1;32m    600[0m ) [38;5;28;01mas[39;00m colxn:
[0;32m--> 601[0m     [43mcolxn[49m[38;5;241;43m.[39;49m[43mwriterecords[49m[43m([49m[43mdf[49m[38;5;241;43m.[39;49m[43miterfeatures[49m[43m([49m[43m)[49m[43m)[49m

File [0;32m/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/fiona/collection.py:549[0m, in [0;36mCollection.writerecords[0;34m(self, records)[0m
[1;32m    547[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mmode [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m ([38;5;124m"[39m[38;5;124ma[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mw[39m[38;5;124m"[39m):
[1;32m    548[0m     [38;5;28;01mraise[39;00m [38;5;167;01mOSError[39;00m([38;5;124m"[39m[38;5;124mcollection not open for writing[39m[38;5;124m"[39m)
[0;32m--> 549[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43msession[49m[38;5;241;43m.[39;49m[43mwriterecs[49m[43m([49m[43mrecords[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[43m)[49m
[1;32m    550[0m [38;5;28mself[39m[38;5;241m.[39m_len [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39msession[38;5;241m.[39mget_length()
[1;32m    551[0m [38;5;28mself[39m[38;5;241m.[39m_bounds [38;5;241m=[39m [38;5;28;01mNone[39;00m

File [0;32mfiona/ogrext.pyx:1408[0m, in [0;36mfiona.ogrext.WritingSession.writerecs[0;34m()[0m

File [0;32mfiona/ogrext.pyx:513[0m, in [0;36mfiona.ogrext.OGRFeatureBuilder.build[0;34m()[0m

[0;31mValueError[0m: Invalid field type <class 'list'>
ValueError: Invalid field type <class 'list'>

